name: Qinyuehu
description: personal blog for learning
url: http://qinyuehu.github.com
markdown: redcarpet
paginate: 5
highlighter: pygments

rss-feed-limit: 10

disqus-id: 
twitter: qinyue
github: qinyuehu
google: 

permalink: /:title
