name: Qinyuehu
description: personal blog for learning
url: http://qinyuehu.github.com
paginate: 5
highlighter: pygments
safe: true
lsi: false
rss-feed-limit: 10

twitter: qinyue
github: qinyuehu
 

permalink: /:title
