name: Qinyuehu
description: personal blog for learning
url: http://qinyuehu.github.com

markdown: redcarpet
paginate: 5
highlighter: pygments

safe: true
lsi: false
encoding: UTF-8
rss-feed-limit: 10
rss-show-full: "no"
twitter: qinyue
github: qinyuehu
 

permalink: /:title
